// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qzybhvufrqzytayufaww.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF6eWJodnVmcnF6eXRheXVmYXd3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5Nzk0NDUsImV4cCI6MjA2OTU1NTQ0NX0.TIgpjaNbZwsrr39hfh61kkqv34AFFJEgZQFWm9LNssY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});